#!/usr/bin/env bash
# Make this machine able to build the GPUI Kit console.
#
# Two things block a stock Fedora-style box that has the *runtime* libraries but not
# the *development* packages, and neither needs root:
#
#   1. `yeslogic-fontconfig-sys` runs pkg-config at build time. `RUST_FONTCONFIG_DLOPEN=1`
#      makes it dlopen `libfontconfig.so.1` at runtime instead. The library is present.
#   2. The linker is passed `-lxcb -lxkbcommon -lxkbcommon-x11`, but only the versioned
#      runtime files (`libxcb.so.1`) exist — the unversioned `.so` symlinks live in the
#      `-dev` packages. We synthesise them into a private directory and add it to the
#      library search path.
#
# Run once. Then plain `cargo build`, `cargo test` and `cargo clippy` work.
set -euo pipefail

repo_root="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
shim_dir="${PARTYTIME_NATIVE_SHIMS:-$HOME/.cache/partytime-native-shims}"

if [[ -d "$shim_dir" && -n "$(ls -A "$shim_dir" 2>/dev/null)" ]]; then
  echo "native shims already present: $shim_dir"
else
  echo "building native shims in $shim_dir"
  mkdir -p "$shim_dir"
  # For every library the loader knows about, expose it under both its SONAME and the
  # unversioned `libfoo.so` name the linker looks for.
  ldconfig -p | awk '/=> \// { print $1, $NF }' | while read -r soname path; do
    [[ -e "$path" ]] || continue
    [[ -e "$shim_dir/$soname" ]] || ln -s "$path" "$shim_dir/$soname"
    unversioned="$(sed -E 's/\.so(\.[0-9]+)*$/.so/' <<<"$soname")"
    [[ "$unversioned" == "$soname" ]] || [[ -e "$shim_dir/$unversioned" ]] ||
      ln -s "$path" "$shim_dir/$unversioned"
  done
fi

mkdir -p "$repo_root/.cargo"
cat >"$repo_root/.cargo/config.toml" <<EOF
# Generated by scripts/setup-build-env.sh — do not edit by hand.
[env]
RUST_FONTCONFIG_DLOPEN = "1"
[build]
rustflags = ["-L", "native=$shim_dir"]
[target.x86_64-unknown-linux-gnu]
rustflags = ["-L", "native=$shim_dir"]
EOF

echo
echo "Wrote $repo_root/.cargo/config.toml"
echo "Verify with: cargo build --workspace"